### ISSUE TITLE
Missing arguments for parameters 'title', 'providerIdToAssign' in call

### ISSUE THREAD

**Issue by mronceray** [nabla/nabla-ios#1]
Hi, I got this issue while building the iOS Example App

<img width="1689" alt="image" src="https://user-images.githubusercontent.com/25317799/175378222-ff6da4e7-6bd6-4023-a7f6-d46f782d09a1.png">

**Comment by tgyhlsb** [comment]
Hi @mronceray and thanks for your feedback.

I'll look into it immediately, in the mean time, you can pass `nil` for both `title` and `providerIdToAssign` to unblock yourselve.

**Comment by tgyhlsb** [comment]
The fix has been released. If you cloned the repository, you can pull the `master` branch. Otherwise bump your dependency to `1.0.0-alpha07`.

Thanks again for your feedback.
